# Generated by Django 5.2.7 on 2025-10-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='services',
            field=models.ManyToManyField(to='landing.service'),
        ),
    ]
