# Generated by Django 5.2.7 on 2025-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_service_enterprise_enterprise_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
