# Generated by Django 5.1.6 on 2025-10-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_enterprise_latitude_enterprise_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='image_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
