# Generated by Django 5.1.6 on 2025-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_enterprise_image_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_enterprise', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_enterprise', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='descritpion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
