# Generated by Django 5.1.6 on 2025-10-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_country_requester_service_descritpion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionactivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
