# Generated by Django 5.1.6 on 2025-10-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_enterprise_brief_sectionactivity_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='brief',
            new_name='description',
        ),
    ]
