# Generated by Django 5.1.6 on 2025-10-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_rename_brief_enterprise_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descritpion',
            new_name='description',
        ),
    ]
