# Generated by Django 5.1.6 on 2025-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_rename_descritpion_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
