# Generated by Django 5.1.6 on 2025-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_enterprise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
