# Generated by Django 5.1.6 on 2025-10-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_alter_enterprise_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requester',
            new_name='Request',
        ),
    ]
