# Generated by Django 5.1.6 on 2025-10-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_alter_request_options_request_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
    ]
